# custom keybindings
keybind = ctrl+f>v=new_split:right
keybind = ctrl+f>s=new_split:down

keybind = ctrl+f>j=goto_split:bottom
keybind = ctrl+f>k=goto_split:top
keybind = ctrl+f>h=goto_split:left
keybind = ctrl+f>l=goto_split:right

keybind = ctrl+f>r=reload_config
keybind = ctrl+f>x=close_surface

keybind = ctrl+f>n=new_window

keybind = ctrl+f>z=toggle_split_zoom

keybind = ctrl+f>e=equalize_splits
keybind = ctrl+f>q=toggle_quick_terminal

keybind = shift+enter=text:\n
keybind = ctrl+enter=text:\n
